### ISSUE TITLE
OOM compiling devSVG.cpp in C++17

### ISSUE THREAD

**Issue by jeroen** [r-lib/vdiffr#137] opened 2023-08-26 11:30 UTC
Since the [switch to c++17](https://github.com/r-lib/vdiffr/commit/41773cbd1dfdf1315123007502eac24659d396e5) your CI [hangs](https://github.com/r-lib/vdiffr/actions/runs/5975314625/job/16211037072) trying to compile `devSVG.cpp` for r-release and r-devel and also pkgdown. The latest versions of R now default to C++17, which causes a massive memory usage, at least on Ubuntu 22.04.

Tested locally that the compilation of `devSVG.cpp` requires about 12GB mem and 10 minutes on ubuntu-22.04 in x64. I am not sure if this is a bug in GCC or expected. I am seeing [the same problem](https://github.com/r-universe/r-lib/actions/runs/5975627290/job/16233525538) on r-universe:

```
* installing to library ‘/usr/local/lib/R/site-library’
  * installing *source* package ‘vdiffr’ ...
  ** using staged installation
  ** libs
  using C++ compiler: ‘g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0’
  g++ -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/cpp11/include'     -fpic  -O2 -ffile-prefix-map=/build/r-base-MHXHhT/r-base-4.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c compare.cpp -o compare.o
  g++ -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/cpp11/include'     -fpic  -O2 -ffile-prefix-map=/build/r-base-MHXHhT/r-base-4.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c cpp11.cpp -o cpp11.o
  g++ -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/cpp11/include'     -fpic  -O2 -ffile-prefix-map=/build/r-base-MHXHhT/r-base-4.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c devSVG.cpp -o devSVG.o
  g++: fatal error: Killed signal terminated program cc1plus
  compilation terminated.
  make: *** [/usr/lib/R/etc/Makeconf:200: devSVG.o] Error 1
  ERROR: compilation failed for package ‘vdiffr’
  * removing ‘/usr/local/lib/R/site-library/vdiffr’
```

**Comment by thomasp85** [comment] 2023-08-28 07:14
I must admit this is above my head but the easy fix seems to turn C++11 back on and inform CRAN of the reasons?

**Comment by krlmlr** [comment] 2023-09-03 04:20
IIUC, you don't need to communicate C++11 in `DESCRIPTION`, perhaps setting `CXXSTD` in `Makevars` is sufficient?

https://github.com/search?q=org%3Acran%20cxxstd&type=code

**Comment by Enchufa2** [comment] 2023-09-09 17:00
What's the gcc version there? I tested this on Fedora with gcc 13.2.1 and, while the compilation takes a lot more time with C++17 compared to e.g. C++14, it takes only a minimal amount of memory.

**Comment by Enchufa2** [comment] 2023-09-09 17:04
Just checked on a `rocker/r-ubuntu:jammy` container with gcc 11.3.0, and I can confirm that the memory usage goes nuts after a few seconds.

**Comment by Enchufa2** [comment] 2023-09-09 17:12
I think the most reasonable fix is to add `CXX_STD = CXX14` to the Makevars files. It was necessary to remove `C++11` from SystemRequirements, but CRAN allows to set C++14 in the Makevars AFAIK.

**Comment by lionel-** [comment] 2023-09-10 06:50
@Enchufa2 Good idea but on old R versions on Windows I'm getting:

```
*** arch - i386
Error in .shlib_internal(args) : 
  C++14 standard requested but CXX14 is not defined
```

I'll probably go back to C++11.

**Comment by lionel-** [comment] 2023-09-10 06:52
Thank you for helping pinpoint the problematic GCC versions by the way. Good to know it seems fixed with more recent GCCs.

**Comment by trevorld** [comment] 2023-09-22 05:05
FYI: "switching" the `gcc` used by Github Actions from the default 11.4.0 to 12.3.0 seems to work for me:

```
      - name: Upgrade gcc to compile vdiffr without error
        if: runner.os == 'Linux'
        run: |
            sudo apt-get install -y g++-12 gcc-12 # probably already installed
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 60
            sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 60
```

**Comment by lionel-** [comment] 2023-09-22 06:26
I'm trying to get a vdiffr update on CRAN, and this time it looks like it will go through :-)

**Comment by lionel-** [comment] 2023-09-22 08:07
On CRAN!

**Closed by lionel-** 2023-09-22 08:07 UTC
