### ISSUE TITLE
"Graphics API version mismatch" with R-devel

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/vdiffr#103] opened 2021-02-12 16:05 UTC
Since downloading the `R-devel` on my system, I can no longer seem to run `vdiffr` tests.

Here is what I see:

```r
> vdiffr::manage_cases()
Running testthat to collect visual cases

  N = New visual case
  X = Failed doppelganger
  o = Successful doppelganger

E
Error: while collecting vdiffr cases. Last error:
* test: plots are rendered correctly
* message: Graphics API version mismatch
You can inspect this error with `vdiffr::last_collection_error()`
Backtrace:
     x
  1. \-vdiffr::manage_cases(filter = "vdiffr")
  2.   \-vdiffr::collect_cases(package, filter = filter, invert = invert)
  3.     +-base::suppressMessages(...)
  4.     | \-base::withCallingHandlers(...)
  5.     \-devtools::test(...)
  6.       \-testthat::test_local(...)
  7.         \-testthat::test_dir(...)
  8.           \-testthat:::test_files(...)
  9.             \-testthat:::test_files(...)
 10.               \-testthat::with_reporter(...)
 11.                 \-reporter$end_reporter()
 12.                   \-testthat:::o_apply(self$reporters, "end_reporter")
 13.                     \-base::lapply(objects, f)
 14.                       \-testthat:::FUN(X[[i]], ...)
 15.                         \-x$end_reporter(...)
```

Session info:

```r
options(width = 200)
library(vdiffr)
sessioninfo::session_info(include_base = TRUE)
#> - Session info ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#>  setting  value                                             
#>  version  R Under development (unstable) (2021-02-11 r79990)
#>  os       Windows 10 x64                                    
#>  system   x86_64, mingw32                                   
#>  ui       RTerm                                             
#>  language (EN)                                              
#>  collate  English_United States.1252                        
#>  ctype    English_United States.1252                        
#>  tz       Europe/Berlin                                     
#>  date     2021-02-12                                        
#> 
#> - Packages -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#>  ! package          * version    date       lib source                                
#>    assertthat         0.2.1      2019-03-21 [1] CRAN (R 4.1.0)                        
#>    backports          1.2.1      2020-12-09 [1] CRAN (R 4.1.0)                        
#>    base             * 4.1.0      2021-02-12 [?] local                                 
#>    cli                2.3.0      2021-01-31 [1] CRAN (R 4.1.0)                        
#>  P compiler           4.1.0      2021-02-12 [2] local                                 
#>    crayon             1.4.1      2021-02-08 [1] CRAN (R 4.1.0)                        
#>  P datasets         * 4.1.0      2021-02-12 [2] local                                 
#>    digest             0.6.27     2020-10-24 [1] CRAN (R 4.1.0)                        
#>    ellipsis           0.3.1      2020-05-15 [1] CRAN (R 4.1.0)                        
#>    evaluate           0.14       2019-05-28 [1] CRAN (R 4.1.0)                        
#>    freetypeharfbuzz   0.2.6      2021-01-11 [1] CRAN (R 4.1.0)                        
#>    fs                 1.5.0      2020-07-31 [1] CRAN (R 4.1.0)                        
#>    gdtools            0.2.3      2021-01-06 [1] CRAN (R 4.1.0)                        
#>    glue               1.4.2      2020-08-27 [1] CRAN (R 4.1.0)                        
#>  P graphics         * 4.1.0      2021-02-12 [2] local                                 
#>  P grDevices        * 4.1.0      2021-02-12 [2] local                                 
#>    highr              0.8        2019-03-20 [1] CRAN (R 4.1.0)                        
#>    htmltools          0.5.1.1    2021-01-22 [1] CRAN (R 4.1.0)                        
#>    knitr              1.31       2021-01-27 [1] CRAN (R 4.1.0)                        
#>    lifecycle          0.2.0      2020-03-06 [1] CRAN (R 4.1.0)                        
#>    magrittr           2.0.1      2020-11-17 [1] CRAN (R 4.1.0)                        
#>  P methods          * 4.1.0      2021-02-12 [2] local                                 
#>    pillar             1.4.7      2020-11-20 [1] CRAN (R 4.1.0)                        
#>    pkgconfig          2.0.3      2019-09-22 [1] CRAN (R 4.1.0)                        
#>    purrr              0.3.4      2020-04-17 [1] CRAN (R 4.1.0)                        
#>    R6                 2.5.0      2020-10-28 [1] CRAN (R 4.1.0)                        
#>    Rcpp               1.0.6      2021-01-15 [1] CRAN (R 4.1.0)                        
#>    reprex             1.0.0      2021-01-27 [1] CRAN (R 4.1.0)                        
#>    rlang              0.4.10     2020-12-30 [1] CRAN (R 4.1.0)                        
#>    rmarkdown          2.6        2020-12-14 [1] CRAN (R 4.1.0)                        
#>    sessioninfo        1.1.1      2018-11-05 [1] CRAN (R 4.1.0)                        
#>  P stats            * 4.1.0      2021-02-12 [2] local                                 
#>    stringi            1.5.3      2020-09-09 [1] CRAN (R 4.1.0)                        
#>    stringr            1.4.0      2019-02-10 [1] CRAN (R 4.1.0)                        
#>    styler             1.3.2.9000 2021-02-08 [1] Github (lorenzwalthert/styler@72b40e4)
#>    systemfonts        1.0.1.9000 2021-02-12 [1] Github (r-lib/systemfonts@bc0b76a)    
#>    tibble             3.0.6      2021-01-29 [1] CRAN (R 4.1.0)                        
#>  P tools              4.1.0      2021-02-12 [2] local                                 
#>  P utils            * 4.1.0      2021-02-12 [2] local                                 
#>    vctrs              0.3.6      2020-12-17 [1] CRAN (R 4.1.0)                        
#>    vdiffr           * 0.3.3      2020-10-06 [1] CRAN (R 4.1.0)                        
#>    withr              2.4.1      2021-01-26 [1] CRAN (R 4.1.0)                        
#>    xfun               0.21       2021-02-10 [1] CRAN (R 4.1.0)                        
#>    yaml               2.2.1      2020-02-01 [1] CRAN (R 4.1.0)                        
#> 
#> [1] C:/Users/inp099/Documents/R/win-library/4.1
#> [2] C:/Program Files/R/R-devel/library
#> 
#>  P -- Loaded and on-disk path mismatch.
```

**Comment by lionel-** [comment] 2021-02-12 16:31
Duplicate of #86 (now pinned).

**Closed by lionel-** 2021-02-12 16:31 UTC

**Comment by jranke** [comment] 2021-02-19 07:12
Isn't the error message rather pointing at the necessity to reinstall vdiffr (embedding svglite)?
