### ISSUE TITLE
Cases in R-devel differ from R 4.0.0

### ISSUE THREAD

**Issue by jranke** [r-lib/vdiffr#86] opened 2020-05-11 08:02 UTC
On travis using r-devel as well as using current r-devel locally, many visual test cases generated with R 4.0.0 fail. It seems that polyline was replaced by polygon and fill: none was added. Example diff:

```
-<polyline points='41.33,168.38 338.83,168.38 338.83,41.33 41.33,41.33 41.33,168.38 ' style='stroke-width: 0.75;' />
+<polygon points='41.33,168.38 338.83,168.38 338.83,41.33 41.33,41.33 ' style='stroke-width: 0.75; fill: none;' />
```

The example test case:

https://github.com/jranke/mkin/blob/master/tests/testthat/test_nafta.R#L25

SVG as generated by R release:

https://raw.githubusercontent.com/jranke/mkin/master/tests/figs/evaluations-according-to-2015-nafta-guidance/nafta-sop-appendix-b.svg

**Comment by lionel-** [comment] 2020-05-11 08:22
This is an upstream change in R-devel.

Maybe we should allow generating multiple SVGs depending on the R version? This is tricky. cc @hadley @thomasp85

**Comment by thomasp85** [comment] 2020-05-11 08:26
Yeah... this is a change in the graphic engine due to a bug reported by me. I think visual testing will always be sensitive to changes in the graphic engine in the same way that unit tests are sensitive to changes in the language...

Seeing as vdiffr is not run on CRAN, can we simply ask users to ignore this while the change rolls over? Having versioned tests will be a lot of complications and infrastructure for relatively little gain

**Comment by lionel-** [comment] 2020-05-11 08:40
Always testing for r-release is much simpler. You're not testing on older R versions in ggplot2?

**Comment by thomasp85** [comment] 2020-05-11 08:41
I'm pretty sure we are not... So you suggest that differ is only run if it detects that the R version is the current release? or that the user should set it up so it only tests on that?

**Comment by lionel-** [comment] 2020-05-11 08:49
It seems we should save users the hassle of having to configure their CI, so the default should be to skip on machines running r-devel or old R? This could be overridden.

**Comment by thomasp85** [comment] 2020-05-11 08:50
Can we detect this reliably without having to update vdiffr with every R release?

**Comment by jranke** [comment] 2020-05-11 13:50
For me it is OK to just test on r-release. I would not want to maintain two sets of test cases... Using testthat, this was easy to configure at the moment using

`skip_if(getRversion() > 4.0)`

**Comment by xrobin** [comment] 2020-05-31 09:44
Just my 2 cents. The check with R-devel is a very nice pre-warning to have.

1. I have more time to fix it, and I can choose when to do it. 
2. It makes it very clear that it's a change in R, and not something wrong with my package. If we only test on R-release, it would mean that one day my CI will fail without a warning before. If I committed something at the same time I'll have no way to know if the issue is in my commit or with the R update.

Personally I will go the other route and skip those tests on R-release.

    skip_if(getRversion() < 4.1)

**Comment by jranke** [comment] 2020-06-03 08:43
Thanks @xrobin for your thoughts, good point. I will stick with R-release for now as I am not routinely testing on R-devel locally. Greetings from Grenzach!

**Comment by IndrajeetPatil** [comment] 2021-05-21 15:31
Since `R 4.1` has now been released, I am wondering if there is any update on this issue.

Although I am currently using the above-suggested `skip_if(getRversion() < 4.1)` solution, this is no longer a sustainable solution. As soon as my work machine is updated to `4.1`, I will no longer have any machine on which I can run these tests locally. And I doubt if I am going to be the only one who will face this problem.

Thanks in advance!

**Comment by lionel-** [comment] 2021-06-08 07:11
We now `skip()` on all R versions < 4.1.0.

**Closed by lionel-** 2021-06-08 07:11 UTC

**Comment by krassowski** [comment] 2021-08-03 14:04
Hi @lionel- I am hitting a reduced test coverage which I reported over at https://github.com/r-lib/covr/issues/486. I am running CI using 3.6 and 4.0 (no 4.1). I am struggling to understand your last comment on skipping on all R versions < 4.1. Does it mean that I have to pin vdiffr to < 1.0 to run tests on 3.6 and 4.0?

**Comment by lionel-** [comment] 2021-08-16 07:32
The vdiffr cases are no longer run on older R versions, which explains the decreased coverage. We might be able to do better with r-lib/testthat#1143 though that's rather long term.

**Comment by pepijn-devries** [comment] 2025-07-11 16:05
Is there any news on this thread? I'm facing the same problem that `vdiffr` tests produce errors when run in R-devel in the R-universe. Should I, or could I just skip these tests when run in R-devel?

**Comment by hadley** [comment] 2025-07-11 16:53
@pepijn-devries given that this issue was closed 4 years ago, I find it unlikely your current problem is the same. I'd suggest filing a new issue with a reprex that illustrates the problem you are having today.
